version: '2'
services:
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=social_db
    volumes:
      - "mongo-store:/data/db"
      - "mongo-config-store:/data/configdb"  
    networks:
      backend:
      
  social-service:
    build: .
    environment:
      - SPRING_ACTIVE_PROFILE=default
      - SERVICE_MANAGEMENT_PORT=8080
      - LOG_FOLDER=/logs
    ports:
      - "8080:8080"
    networks:
      backend:
        
networks:
  backend:
     driver: bridge
volumes:
   mongo-store:
   mongo-config-store:         